---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Network Benchmark: global (wrapper)'
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  S3BucketName:
    Description: 'A wrapper for the S3BucketName'
    Type: String
  IAMInstanceProfileName:
    Description: 'A wrapper for the IAMInstanceProfileName'
    Type: String
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${AWS::StackName}-client'
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
  SecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Sub '${SecurityGroup.GroupId}'
      IpProtocol: tcp
      FromPort: '5201'
      ToPort: '5201'
      SourceSecurityGroupId: !Sub '${SecurityGroup.GroupId}'
Outputs:
  SecurityGroupId:
    Description: 'The security group id allowing traffic for iperf3.'
    Value: !Sub '${SecurityGroup.GroupId}'
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'
  S3BucketName:
    Description: 'The name of the S3 bucket storing the network benchmark results.'
    Value: !Ref S3BucketName
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'
  IAMInstanceProfileName:
    Description: 'The name of the IAM instance profile granting write access to S3 for storing network benchmark results.'
    Value: !Ref IAMInstanceProfileName
    Export:
      Name: !Sub '${AWS::StackName}-IAMInstanceProfileName'
